sudo: false
language: rust

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - |
      which cargo-coveralls || cargo install cargo-travis
      export PATH=$HOME/.cargo/bin:$PATH
script:
  - |
      cargo build -v
      cargo test -v
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench -v --no-run --all-features;
      fi
      cargo doc -v
after_success:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
        cargo coveralls --exclude-pattern tests/;
      fi